[project]
name = "mcp-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.5.1",
    "openai-agents-mcp>=0.0.8",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
